### ISSUE TITLE
Firefox extension is missing

### ISSUE THREAD

**Issue by ASalazarMX** [ricwtk/sync-bookmarks#1]
The Firefox extension is missing from the [Mozilla Add-ons website](https://addons.mozilla.org/en-GB/firefox/addon/sync-bookmarks/).

**Comment by ricwtk** [comment]
There was a bit of issue which didn't pass Mozilla's review policies so it was taken down by Mozilla. I have modified it to be compatible with the policies. You should be able to find it now.
